---
- hosts: webservers
  become: true
  tasks:
  - name: Installing httpd package
    yum: name=tree state=latest
  - name: Start the httpd service
    service : name=httpd state=started
  - name: Copy the index.html
    copy: src=/etc/ansible/index.html dest=/var/www/html
