---
 - name:  Provisioning EC2 instances using Ansible Playbook
   hosts: webservers
   connection: local
   gather_facts: False
   tags: provisioning

# Defining Variables for EC2 provisioning
   vars:
     keypair: testnc
     instance_type: t2.micro
     image: ami-0fd61683ae1a27a64
     wait: yes
     group: webserver
     count: 1
     region: us-west-1
     security_group: myec2-security-grp
   
   tasks:

     - name: Task # 1 - Create my security group and Ports to be open
       local_action: 
         module: ec2_group
         name: "{{ security_group }}"
         description: Security Group for webserver Servers
         region: "{{ region }}"
         rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
         rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
       register: basic_firewall
     - name: Task # 2 Launch the new EC2 Instance
       local_action:  ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
       register: ec2
     - name: Task # 3 Add Tagging to EC2 instance
       local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
       with_items: "{{ ec2.instances }}"
       args:
         tags:
           Name: EC2_Instance_by_playbook

